baseURL = 'http://example.org'
languageCode = 'en-us'
defaultcontentlanguage = "en"
title = "</Rxfa>"
Theme = 'hugo-coder'

[params]
  author = "Rxfa"
  info = "All things web"
  description = "Rxfa's personal website"
  keywords = "blog,developer,personal, hacking, web"
  avatarurl = "pfp.jpg"
  colorScheme = "dark"
  since = 2022

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Rxfa/"



# Menu links
#[[menu.main]]
#  name = "Projects"
#  weight = 1
#  url  = "projects/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Categories"
  weight = 3
  url  = "categories/"
[[menu.main]]
  name = "Tags"
  weight = 4
  url  = "tags/"